name: upload my image to DockerHub
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build
        run: docker build . --tag ${{ secrets.DOCKER_USER }}/chome:latest

      - name: push to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/chome:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            sudo docker stop chome
            sudo docker rm chome
            sudo docker rmi shahargut/chome
            sudo docker pull shahargut/chome
            sudo docker run --name chome -d -p 80:3000 shahargut/chome